site_name: Neural Functional Networks

plugins:
  - mkdocstrings
  - search

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
  palette:
    primary: blue

nav:
  - nfn.common:
    - NetworkSpec: /nfn-docs/nfn.common/#nfn.common.NetworkSpec
    - WeightSpaceFeatures: /nfn-docs/nfn.common/#nfn.common.WeightSpaceFeatures
    - state_dict_to_tensors(): /nfn-docs/nfn.common/#nfn.common.state_dict_to_tensors
    - params_to_state_dicts(): /nfn-docs/nfn.common/#nfn.common.params_to_state_dicts
    - network_spec_from_wsfeat(): /nfn-docs/nfn.common/#nfn.common.network_spec_from_wsfeat
  - nfn.layers:
    - NPPool: /nfn-docs/nfn.layers/#nfn.layers.NPPool
    - HNPPool: /nfn-docs/nfn.layers/#nfn.layers.HNPPool
    - Pointwise: /nfn-docs/nfn.layers/#nfn.layers.Pointwise
    - NPLinear: /nfn-docs/nfn.layers/#nfn.layers.NPLinear
    - HNPLinear: /nfn-docs/nfn.layers/#nfn.layers.HNPLinear


repo_url: https://github.com/AllanYangZhou/nfn/

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences